### ISSUE TITLE
Typo in `customer_inquiry_assistant.py`

### ISSUE THREAD

**Issue by shahrishabh7** [MrXandbadas/openAI_Assistant_API_DEMO#1]
There's a small typo on line 13 - "My_First_Chat" requires closing quotes.
`import asyncio
from agent_class import OAI_Agent

api_key="APIKEY"
organization_id="ORGID"

client = OAI_Agent(api_key=api_key, organization_id=organization_id)

json_file = 'thread_data.json'
agent_file = 'agent_data.json'

thread_name = "My_First_Chat
Customer_Service_Assistant = {
    "name":"Customer Service Assistant",
    "instructions":"You are a customer service assistant. Answer user queries courteously and accurately.",
    "tools":[{"type": "retrieval"}],
    "model":"gpt-4-1106-preview"
}
`

**Comment by MrXandbadas** [comment]
Thanks for that
